### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 2015,
    "price": 20000,
    "milage": 10000,
    "latitude": 40.7128,
    "longitude": 74.0060
}

### Approve an existing report
PATCH http://localhost:3000/reports/5f26f8e1-b80d-44a2-8c86-38cefd1bc0c8
Content-Type: application/json

{
    "approved": true
}