### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@test.com",
    "password": "test"
}

### Login


POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "a@test.com",
    "password": "test"
}

### Signout
POST http://localhost:3000/auth/signout

### Who am I route

GET http://localhost:3000/auth/whoami
